name: 'Deploy to Server'

# Evento / Trigger para el workflow
on:
  push:
    branches:
      - main

jobs:
  first-job:
    # Especicamos el runner que se usará
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

  second-job:
    # Especicamos el runner que se usará
    needs: first-job
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola mundo
        run: echo "Hola mundo dos"