name: 'Deploy to Server'

# Evento / Trigger para el workflow
on:
  push:
    branches:
      - main

jobs:
  first-job:
    # Especicamos el runner que se usará
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hacemos pull del código"